### ISSUE TITLE
Can this library be used for recommending similar users?

### ISSUE THREAD

**Issue by vitobotta** [ankane/vowpalwabbit-ruby#3]
I am reading a bit but am still confused. I am wondering if it can do what for example Disco and Cmfrec can do with recommendations and whether it would be better or worse. Thanks in advance for any advice

**Comment by ankane** [comment]
Hey @vitobotta, I haven't tried it for this, but Vowpal Wabbit does support [matrix factorization](https://github.com/mritunjaysharma394/vowpal-wiki/blob/master/Matrix-factorization-example.md) (at least for explicit feedback), so you could use it to generate user factors and then use cosine distance to get similar users.

**Comment by vitobotta** [comment]
I see, thanks!
